services:
  parser:
    build: .
    image: node:22.15.0
    ports: 
    - "8080:80"
    volumes:
      - ./inbound:/usr/src/inbound
      - ./outbound:/usr/src/outbound
      - ./processed:/usr/src/processed